# Generated by Django 3.2.3 on 2021-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('roll', models.CharField(max_length=10, unique=True)),
                ('branch', models.CharField(max_length=10)),
                ('dateOfJoin', models.DateField()),
            ],
        ),
    ]
