# Generated by Django 4.0.4 on 2022-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.CharField(max_length=36)),
                ('OTP', models.CharField(max_length=10)),
                ('isStudent', models.BooleanField()),
            ],
        ),
    ]
