# Generated by Django 3.2.3 on 2021-09-30 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('regNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('branch', models.CharField(max_length=10)),
                ('dateTimeOfJoin', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 15, 27, 14, 239581))),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('mailId', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('branch', models.CharField(max_length=10)),
                ('dateTimeOfJoin', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 15, 27, 14, 259788))),
            ],
        ),
    ]
