# Generated by Django 3.2.9 on 2021-12-03 04:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sID', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('regNumber', models.IntegerField(unique=True)),
                ('password', models.TextField()),
                ('branch', models.CharField(max_length=10)),
                ('dateTimeOfJoin', models.DateTimeField(
                    default=datetime.datetime(2021, 12, 3, 9, 53, 23, 282104))),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tID', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mailId', models.CharField(max_length=25, unique=True)),
                ('password', models.TextField()),
                ('branch', models.CharField(max_length=10)),
                ('dateTimeOfJoin', models.DateTimeField(
                    default=datetime.datetime(2021, 12, 3, 9, 53, 23, 335488))),
            ],
        ),
    ]
