# Generated by Django 3.2.9 on 2021-12-04 18:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quentions',
            fields=[
                ('qID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('dateTimeOfPost', models.DateTimeField(default=datetime.datetime(2021, 12, 5, 0, 10, 2, 854040))),
                ('likeCount', models.IntegerField(default=0)),
                ('disLikeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='dateTimeOfJoin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 0, 10, 2, 723471)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dateTimeOfJoin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 0, 10, 2, 854040)),
        ),
    ]
