# Generated by Django 3.2.9 on 2021-12-02 18:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teachers',
            name='tID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='dateTimeOfJoin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 23, 36, 48, 791846)),
        ),
        migrations.AlterField(
            model_name='students',
            name='regNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dateTimeOfJoin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 23, 36, 48, 907751)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='mailId',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
