# Generated by Django 3.2.9 on 2021-12-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211205_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='dateTimeOfPost',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quentions',
            name='dateTimeOfPost',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='dateTimeOfJoin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dateTimeOfJoin',
            field=models.DateTimeField(),
        ),
    ]
