# Generated by Django 3.2.9 on 2021-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_answers_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='uID',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quentions',
            name='uID',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
    ]
