# Generated by Django 3.2.9 on 2021-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211207_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='reactionRecord',
            new_name='dislikeRecord',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='reactionRecord',
            new_name='dislikeRecord',
        ),
        migrations.AddField(
            model_name='students',
            name='likeRecord',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='likeRecord',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
