# Generated by Django 4.0 on 2021-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211208_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='quentions',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
