# Generated by Django 4.0 on 2021-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_quentions_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='byStudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quentions',
            name='byStudent',
            field=models.BooleanField(default=True),
        ),
    ]
