# Generated by Django 4.0.4 on 2022-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_students_isverified_teachers_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quentions',
            name='category',
            field=models.CharField(default='CSE', max_length=10),
            preserve_default=False,
        ),
    ]
